MODEL_NAME: AS_het_agent
defaults:
  - params: AS_het_agent
GP_MODEL: 
  name:  ExactGPModel #ASGPModel #SpectralMixtureModel #ExactGPModel #DeepKernel
  config:
    active_dim: 4
EXPECT_OP: 
  name: SinglePoint
