MODEL_NAME: StochasticOptimalGrowthModel
GP_MODEL: 
  name: ASGPModel
  config:
    active_dim: 2
EXPECT_OP: 
  name: MCAdditiveStandardNormal
  config:
    n_mc_sample: 10 
    sigma: 1e-2
# number of monte-carlo sample pointds for integration
defaults:
  - params: SOGM 