A: 12
N: 2
Z: 2
tfp: # [discrete_state][tfp_i]
  - - 0.95
    - 0.95
  - - 0.95
    - 1.05
  - - 1.05
    - 0.95
  - - 1.05
    - 1.05  
alpha: 0.3
beta: 0.815
gamma: 2
delta: 0.37
pi: # ["pi"][prev_state][new_state]
  - - 0.25
    - 0.25
    - 0.25
    - 0.25
  - - 0.25
    - 0.25
    - 0.25
    - 0.25
  - - 0.25
    - 0.25
    - 0.25
    - 0.25
  - - 0.25
    - 0.25
    - 0.25
    - 0.25
L:
  - 1
  - 1
l:
  - 0.75
  - 0.9375
  - 1.125
  - 1.3125
  - 1.5
  - 1.5
  - 1.5
  - 1.5
  - 1.5
  - 0.95
  - 0.4
  - 0.4
